# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/abaisero/pre-commit-hooks
    rev: 0.1.0
    hooks:
    -   id: no-commit
        exclude: pre-commit-config.yaml
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort 
    rev: 5.7.0
    hooks:
    -   id: isort
